name: Backend CI/CD

on:
  pull_request_target:
    branches: [ main ]
    paths:
      - 'se2025BackEnd/**'
    

jobs:
  backend-build-test:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # 明确指定PR源分支
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Build backend
        working-directory: se2025BackEnd
        run: mvn package -DskipTests

  backend-deploy:
    needs: backend-build-test
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # 明确指定PR源分支
          fetch-depth: 0
      
      - name: Set up JDK for deploy
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Build backend JAR
        working-directory: se2025BackEnd
        run: mvn package -DskipTests
          
      - name: Transfer backend files to Huawei Cloud
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r se2025BackEnd/target/*.jar Administrator@${{ secrets.HUAWEI_SERVER_IP }}:"C:/Users/Administrator/project/temp/deploy/target/"

      - name: Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HUAWEI_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 30m
          script: |
              powershell.exe -ExecutionPolicy Bypass -Command "
              # 获取8080端口进程ID并停止
              `$processId = (netstat -ano | findstr :8080 | findstr LISTENING | Select-Object -First 1) -split '\\s+' | Select-Object -Last 1
              if (`$processId) {
                Write-Host \"Stopping process (PID: `$processId)\"
                Stop-Process -Id `$processId -Force
                Start-Sleep -Seconds 3
              }
              # 部署新版本
              mkdir 'C:\Users\Administrator\project\backend' -Force
              Copy-Item 'C:\Users\Administrator\project\temp\deploy\target\*.jar' 'C:\Users\Administrator\project\backend\' -Force
  
              # 启动服务 - 使用具体文件名
              $jarPath = 'C:\Users\Administrator\project\backend\project-0.0.1-SNAPSHOT.jar'
              Start-Process -FilePath 'java' -ArgumentList '-jar', $jarPath -NoNewWindow -WorkingDirectory 'C:\Users\Administrator\project\backend'

              # 验证启动
              Start-Sleep -Seconds 10
              if (netstat -ano | findstr :8080) {
                Write-Host '✅ Backend service started'
              } else {
                Write-Host '❌ Backend service failed'
                exit 1
              }
              "